name: Commit Message Lint

on:
  pull_request:
    branches: [main, dev, qa, prod]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml



