name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main, dev, qa, prod]

jobs:
  commitlint:
    name: Check Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/{config-conventional,cli}
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js


