name: Commit Lint

on:
  pull_request:
    branches: [main, qa, dev] # Update based on your repo branches

jobs:
  lint-commits:
    name: Validate PR commit messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Check Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            style
            test
          requireScope: false
