name: CD

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ github.ref_name }} environment..."
          # Simulated deploy command
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "Deploying to Development server"
            # ./deploy-dev.sh or npm run deploy-dev
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "Deploying to QA server"
            # ./deploy-qa.sh or npm run deploy-qa
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "Deploying to Production server"
            # ./deploy-prod.sh or npm run deploy-prod
          fi
